### ISSUE TITLE
User register - All users

### ISSUE THREAD

**Issue by DasunThathsara** [La-Fresca/la-fresca-frontend#54]

**Comment by iamtrazy** [comment]
Registrations works, if UI changes are required reopen

**Comment by iamtrazy** [comment]
closing

**Comment by DasunThathsara** [comment]
First name and last name are required. Check the user model in the backend.

**Comment by iamtrazy** [comment]
fixed in [8d6c3fb](https://github.com/La-Fresca/la-fresca-frontend/commit/8d6c3fbd020d387102346c00b913d7a18ce8f9e5)](https://github.com/La-Fresca/la-fresca-frontend/commit/8d6c3fbd020d387102346c00b913d7a18ce8f9e5). reopen if neccesary
